### ISSUE TITLE
工作人員名單

### ISSUE THREAD

**Issue by david50407** [COSCUP/coscup2018-website#11]
我們需要列出本次的工作人員名單，
如此一來才能讓訪客知道本次活動的工作人員有哪些，
需要的資訊包括但不限於：

* 組別資訊
* 工作人員名稱
* （工作人員頭像）

**Comment by nfsnfs** [comment]
我覺得這個可以不用在上線前，留到上線後在處理好嗎?

**Comment by david50407** [comment]
@nfsnfs 行，不過要先把網站上的 dummy data 拔掉XD

**Comment by nfsnfs** [comment]
https://docs.google.com/spreadsheets/d/10ikJpDdQENQePuQ1g0EXcPErxjpxoyu7DCwUF7BDA3M/edit#gid=0

工人名單

**Comment by david50407** [comment]
我有從 grass 那邊拿到一個 list

我把他轉成 json 了，在 https://script.google.com/a/coscup.tw/macros/s/AKfycbxz2kOgLEPrk1fjvO6jWAFdOKkQquR4SpU2R2Zv6KgEvwXqk5Di/exec 可以看到

在 https://github.com/COSCUP/coscup2018-website-api/pull/9 有更新
