### ISSUE TITLE
交通路線指引

### ISSUE THREAD

**Issue by david50407** [COSCUP/coscup2018-website#12]
除了交通方式說明以外，
也許我們能夠提供點選交通方式即導引至地圖應用程式的路線規劃，
讓訪客可以更容易了解交通方式的說明

**Comment by PichuChen** [comment]
這個部分好像沒有通用的Schema的樣子，看起來都是用 a href="https://... ... 下去處理的

**Comment by david50407** [comment]
沒關係 我覺得這個沒有這麼急著做，可以慢慢花時間改善

**Comment by david50407** [comment]
fixed at https://github.com/COSCUP/coscup2018-website/commit/0e0677f27db1419e8d75062592ca943db25583c5
