### ISSUE TITLE
英文翻譯

### ISSUE THREAD

**Issue by david50407** [COSCUP/coscup2018-website#13]
目前只有繁體中文的翻譯是完整的，
我們還需要英文的內容翻譯，
這樣熟悉英文的訪客才能透過網站了解活動內容，包括但不限於下列頁面：

* [x] about
* [x] transportation
* [x] sponsors
* [x] staffs

**Comment by PichuChen** [comment]
英文翻譯有特別的工具嗎？另外是地圖的部分我看到先前是Transport, 這次好像變了，網址和標題還不一樣。

**Comment by david50407** [comment]
我不知道 Transport 跟 Directions 哪個比較好，有沒有比較熟悉這類英文使用的朋友可以協助一下？

**Comment by david50407** [comment]
@PichuChen 目前沒有比較好的翻譯工具
只能透過編輯[網站語系檔](https://github.com/COSCUP/coscup2018-website/blob/dev/languages/en.ts) 以及 [API Data](https://github.com/COSCUP/coscup2018-website-api/tree/master/src/en) 來完成編輯

有在打算使用 Google spreadsheet 來編輯並對照翻譯並自動產生 API 的計畫

**Comment by PichuChen** [comment]
Transport和Directions 的部分，我認為用名詞型的 Transportation比較好
以下是範例參考
https://www.ces.tech/Logistics/Transportation.aspx

**Comment by david50407** [comment]
我目前選擇 Directions 的原因只是比較短⋯⋯XDDDD
當然如果最後 Transportation 比較適當就換過去

另外我看到也有不少 conf 是用 venue 或是 location，
我覺得也都是可以參考的選項

**Comment by nfsnfs** [comment]
我個人比較常看到的是 Venue :p

**Comment by nfsnfs** [comment]
交通: http://www-e.ntust.edu.tw/files/14-1089-39721,r640-1.php 

> By the Taipei Joint Bus System
> Bus lines within the system that make a stop at Taiwan Tech are: #1, #207, #275, #275(Sub), #275(Shuttle), #650, #672, #673, #907, #11(Green Line), #12 (Brown Line), Dunhua Main Line.
> ​
> By Express Bus (via freeway or expressway)
> Fuho Bus (Banqiao—Keelung; Taipei—Keelung; Xindian—Keelung; De-Lin Institute of Technology—Keelung)
> Keelung Bus (Banqiao—Keelung)
> Zhinan Bus/ Chungli Bus (Taoyuan—Taipei City Hall Bus Station): serves Xindian District, Gongguan, and Liuzhangli.
> Taichung Bus/CitiAir Bus (Taichung-Taipei): serves Longtan and Xindian Districts, Liuzhangli, Taipei City Hall Bus Station, and Songshan Railway Station.
> King Bus/e-go Bus/Chungli Bus (Chungli—Taipei): serves Yonghe and Zhonghe Districts, Gongguan, Liuzhangli, and Taipei City Hall Bus Station.
> Yalan Bus (Hsinchu—Taipei): except Taiwan Tech, serves Industrial Technology Research Institute, National Tsing Hua University, National Chiao Tung University, Hsinchu Science and Industrial Park, Longtan and Xindian Districts, several MRT stations (Jingmei, Wanlong, and Gongguan), Xinsheng South Road, and Ren-Ai and Dunhua Intersection (located within walking distance of Taipei City Government).
> ​
> By the MRT
> Songshan-Xindian Line: Leave the Gongguan station (G07) via Exit 2 (leading to Mingchuan Elementary School) and go left onto Zhoushan Road on the NTU campus and walk a short way to Lu-Ming Hall (鹿鳴堂). Turn right and head to Keelung Road. Cross the road and turn left into an entrance of the Taiwan Tech campus. Or take a short ride to Taiwan Tech on the #1, #673, #907, #11(Green Line), or #12 (Brown Line) bus from Exit 1 of the Gongguan station.
> Wenhu Line: Ride Keelung Bus (Keelung-Banqiao) or the #1, #207, #672, or #650 bus from the Liuzhangli station (BR07).

 
 
Getting from the Airport to Taiwan Tech:
The most direct and least expensive transportation is by one of the airport buses run by the Taiwan Bus Corp. After you exit the immigration and customs area, look for signs that say Airport Bus  機場巴士  These signs will bring you to the bus stop area of the terminal, where you can buy tickets for the bus.  Buy a ticket for either the Kuokuang Line 國光號 or the Chunghsin Line 中興號 , which have the fewest stops between the airport and Taipei.
 
There are compartments under the bus which will be open for you to put your luggage in before you get on the bus.  Don’t forget to get your luggage when you get off the bus!
 
Stay on the bus until the last stop, which will be near the Taipei Railway Station (台北車站) or the Sungshan Domestic Airport (松山機場) inside Taipei. (It really is inside the city!) When you get off the bus, the driver should open the compartment to let you take out your luggage.  If he doesn’t, show the driver the following words: 行李 Luggage
 
Once you have gotten off the bus and have picked up your luggage, look for a taxi. Show the driver the address of our school: 國立台灣科技大學 基隆路四段43號 National Taiwan University of Science and Technology 43 Keelung Road, Section 4

**Comment by david50407** [comment]
@nfsnfs 你覺得直接複製貼上可以嗎？ 我看像是中文版本的交通說明就感覺應該需要被修改一下……

**Comment by nfsnfs** [comment]
我覺得要修改一下 ... 第一個是這也太長了啦，中文版本的部分就只留下捷運和開車，然後補上 OSM / Google maps ...

**Comment by david50407** [comment]
@nfsnfs 參考一下這個 issue  https://github.com/COSCUP/coscup2018-website/issues/8 裡面我有先列一些交通方式了，你看看合不合適

**Comment by Duocat** [comment]
最前面或許可以先加一段敘述：「如果有網路可用的會眾，請參考 Google Maps，設定目的地到台灣科技大學，並遵循 Google Maps 之指引。 」這樣可以用 Google Maps 的會眾就不用看下面那一堆了。Google Maps 的大眾運輸導航在台北這一段可以說十分完備了。

**Comment by david50407** [comment]
@Duocat 我打算在各種交通方式的旁邊加上「在 Google Maps 開啓」的按鈕，自動打開 google map 並且先選好導航跟交通方式，你覺得這樣如何？

ref: https://developers.google.com/maps/documentation/urls/guide#directions-action

**Comment by david50407** [comment]
已在 https://github.com/COSCUP/coscup2018-website/commit/0e0677f27db1419e8d75062592ca943db25583c5 新增「在 Google Maps 中開啓」的按鈕

**Comment by hachumeow** [comment]
參考 Staging 的網站翻譯都放在這份 Google doc 上面 我會陸續翻完：https://docs.google.com/document/d/11dDPlbHWJFhJJFY5kbhB5bGrdr5YmBEFPLkPNExYWuI/edit?usp=sharing

**Comment by david50407** [comment]
@hachumeow 鈦金級是後來新增的嗎？

**Comment by david50407** [comment]
All pages are finished. Close this issue.
