### ISSUE TITLE
網站 RWD 處理

### ISSUE THREAD

**Issue by PichuChen** [COSCUP/coscup2018-website#15]
目前測試上英文版接近無法使用，中文版大致上還能使用，只是視覺上跑掉。

**Comment by david50407** [comment]
Yes, 目前還沒有針對 RWD 做優化
我要來改變一下你的標題，讓主旨更貼切

**Comment by david50407** [comment]
我開始在處理 RWD 的部分了，從 container 大小開始調整 https://github.com/COSCUP/coscup2018-website/commit/12daa14f65c8cb79988286aa7400a5c5df927369

之後還有 navbar 跟 footer 要改造……

**Comment by david50407** [comment]
fixed at https://github.com/COSCUP/coscup2018-website/commit/b594156b087a6d7cf7a4144c4419fd2d365048f1
https://github.com/COSCUP/coscup2018-website/commit/a271cbb45a1cc4f28b0dd5e4358dd9a14991717c
https://github.com/COSCUP/coscup2018-website/commit/bb11e254fb2a2013a8c21f9463536193ef33fe3a
