### ISSUE TITLE
網站標題應為 COSCUP x GNOME.Asia x openSUSE.Asia

### ISSUE THREAD

**Issue by david50407** [COSCUP/coscup2018-website#18]
此次活動為「COSCUP x GNOME.Asia x openSUSE.Asia」三方掛名聯合舉辦，
因此我們需要在網站上面露出「COSCUP x GNOME.Asia x openSUSE.Asia」的擡頭，
這樣訪客才能容易理解此次活動的主體。

**Comment by david50407** [comment]
fixed at https://github.com/COSCUP/coscup2018-website/commit/7ff1d30cfc43f66a9073fd309c763b860467262f

**Comment by othree** [comment]
blog 的連結算不算也是外部的？

**Comment by david50407** [comment]
@othree 什麼意思？
