### ISSUE TITLE
地圖標記位置不精準

### ISSUE THREAD

**Issue by CrBoy** [COSCUP/coscup2018-website#2]
應將 Google Maps 的標記位置定在 IB 門口，方便會眾依照地圖找到會場

**Comment by david50407** [comment]
我覺得應該是 `(25.0130494,121.5402862)` 你們覺得呢？

**Comment by snoopy60313** [comment]
從台科大門進來，IB 門口會在紅色箭頭標示的位子。(25.013454,121.540429)
![2018-05-21 12 48 38](https://user-images.githubusercontent.com/11918794/40291164-b762d2d6-5cf5-11e8-861b-5f40ee9090be.png)
