### ISSUE TITLE
報名資訊文案

### ISSUE THREAD

**Issue by david50407** [COSCUP/coscup2018-website#7]
目前針對報名的資訊只有報名開放時間，
我們也許需要更多文字，
來引導大家進行報名參加

**Comment by nfsnfs** [comment]
在 KKTIX 上的報名文案基本上也是用之前那個 event description ...

> 
> 開源人年會 COSCUP 已經邁入第十三年了，今年的活動有些特別，除了延續去年首次嘗試的社群議程外，今年更與 GNOME.Asia 與 openSUSE.Asia 一起合辦，今年的時間地點則於 8/11-12 在台灣科技大學國際大樓舉辦。過去，COSCUP 由各地社群共同舉辦，在眾多同好的參與下，逐漸成長茁壯，今年除了有在地社群成為議程的協力夥伴外，更加入了國際社群們，希望能打造更多元的主題和議程。無論你是寫 open source 軟體的開發者、熱衷 open source 軟體的推廣者、熟悉 open source 軟體的使用者或是想了解 open source 軟體的新手，都歡迎你來參加一年一度全台最大的 COSCUP x GNOME.Asia x openSUSE.Asia 2018!
> 
>     活動列表：社群議程、工作坊
> 
>     地點：台灣科技大學 國際大樓
> 
>     日期：8/11 - 8/12     
> 
>     開源貢獻者 VIP 報名：6/2（需有邀請碼才能報名）
> 
>     一般會眾報名：6/20 晚上 8:00
> 
>  
> 開源香油錢
> 
> COSCUP 的宗旨在於提供一個聯結開放原始碼開發者、使用者與推廣者的平台。希望藉由每年一度的研討會，來推動自由及開放原始碼軟體（FLOSS）。想對開源精神盡一點心力，除了身體力行來參與 COSCUP 以外，也可以考慮贊助香油錢，使今年 COSCUP x GNOME.Asia x openSUSE.Asia 的運作更為順利。假使您有意願，請點選 PLUS TWD $500 / $2,500 / $5,000 donation 的票種，如下圖所示，感謝您的配合。

**Comment by nfsnfs** [comment]
> COSCUP celebrates its 13th anniversary this year. Over the past decade, the event has co-operated with communities all over the world. With everyone's involvement, COSCUP grows up. This year, COSCUP will co-host with GNOME.Asia and openSUSE.Asia in National Taiwan University of Science and Technology on 8/11-12. And several communities will be the program partners to provide disversified topics and talks. 
> 
>  
> 
> Whoever you are an Open Source coder, a devoted Open Source promoter, an user familiar with Open Source, or even a newcomer, we sincerely welcome you to be a part of COSCUP x GNOME.Asia x openSUSE.Asia 2018! 
> 
>  
> 
>     List of Activities: usual program, workshop
> 
>     Location: International Building, National Taiwan University of Science and Technology（台灣科技大學國際大樓）
> 
>     Date: 8/11 - 8/12
> 
>     Open Source Contributor VIP Registration: 6/2 (invitation code required)
> 
>     Normal Registration : 6/20 8:00pm
> 
>  
> Open Source Donations
> 
> Want to do something in the spirit of Open but don’t know where to start? As well as coming to COSCUP x GNOME.Asia x openSUSE.Asia in person, you may consider donations that will help it run smoother. If you feel like doing so, please choose the “Plus TWD $500 / $2,500 / $5,000 donation” type of ticket (as shown below). Thank you for your consideration.

**Comment by david50407** [comment]
fixed at https://github.com/COSCUP/coscup2018-website/commit/fad275ca10af13acec728221bd45d756c67c5167
