### ISSUE TITLE
交通方式說明

### ISSUE THREAD

**Issue by david50407** [COSCUP/coscup2018-website#8]
目前網站放置的交通方式為 2017 年的交通方式，
我們需要更新成今年在 NTUST IB 的交通方式，
這樣與會者才能清楚了解該如何到場參加本次會議，包含但不限於：

* 台北捷運
* 公車
* 自行開車
* 機場捷運、高鐵（針對來自外國與會者可能會需要，大家不一定會知道要怎麼抵達台北市）

**Comment by david50407** [comment]
可以參考： http://www.ntust.edu.tw/files/11-1000-101.php

**Comment by david50407** [comment]
extracted from https://github.com/COSCUP/coscup2018-website/issues/13#issuecomment-390483686

english reference: http://www-e.ntust.edu.tw/files/14-1089-39721,r640-1.php

**Comment by david50407** [comment]
https://developers.google.com/maps/documentation/urls/guide#directions-action

Place ID: `ChIJm1FDqyGqQjQRGm-aCGnsj9A`

**Comment by alznn** [comment]
簡單整理交通方式與文案，給您參考，看是否需要新增其他資料，
連結：http://bit.ly/2IPKkht

**Comment by slouchy** [comment]
透過 Android 手機打開下方連結，會自動跳至 Google 地圖並以自行開車的方式做現在位置和台灣科技大學間的導航規劃

https://www.google.com.tw/maps/dir/?api=1&travelmode=driving&destination=National%2c+Taiwan%2c+University%2c+of%2c+Science%2c+and%2c+Technology

**Comment by david50407** [comment]
@alznn 自行開車前往的話有沒有停車指引呢？

**Comment by alznn** [comment]
@david50407  我有找到停車指引，但不確定離國際大樓的位置，若沒關係的話我可以再補上停車指引

**Comment by slouchy** [comment]
@david50407  
ChIJm1FDqyGqQjQRGm-aCGnsj9A 這串 placeID 依舊是指向台灣科技大學，和直接搜尋台灣科技大學是相同的

**Comment by david50407** [comment]
@slouchy 這就怪了 除非 Google Maps 騙我
不然這個 place id 應該是 IB 而不是 NTUST 這個地標⋯⋯

![42721458-10ef-4145-8bb9-0644415ad7bf](https://user-images.githubusercontent.com/841969/40295704-edc5706a-5d0c-11e8-876a-deb27d222979.png)

**Comment by david50407** [comment]
欸⋯⋯我犯傻了 原來是我貼錯 id
應該是這個 `ChIJkzOyriGqQjQR67ly89oFfLo`

**Comment by david50407** [comment]
@alznn 我覺得停車資訊有可能是需要的，麻煩你了

**Comment by david50407** [comment]
已在
* https://github.com/COSCUP/coscup2018-website-api/commit/66078872dfad8b447a8c55def6bb101b8241210f 更新交通方式說明
* https://github.com/COSCUP/coscup2018-website/commit/0e0677f27db1419e8d75062592ca943db25583c5 新增「在 Google Maps 中開啓」的按鈕
